name: Windows
on: 
  workflow_dispatch:
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build 
